- name: 更新並升級 apt 套件
  apt:
    update_cache: yes
    upgrade: 'yes'

- name: 安裝常用 apk 套件
  apt:
    name:
      - wget
      - curl
      - unzip
      - gnupg2
      - vim
      - git
      - openssl
    state: present
