- name: 添加 PHP PPA 儲存庫
  apt_repository:
    repo: ppa:ondrej/php

- name: 安裝 PHP 及其擴展
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - php{{ php_version }}-fpm
    - php{{ php_version }}-mysql
    - php{{ php_version }}-xml
    - php{{ php_version }}-mbstring
    - php{{ php_version }}-json
    - php{{ php_version }}-zip
    - php{{ php_version }}-gd
    - php{{ php_version }}-curl
    - php{{ php_version }}-pear
    - php{{ php_version }}-dev
    - php{{ php_version }}-cli
    - php{{ php_version }}-tokenizer
    - php{{ php_version }}-bcmath
